import { describe, expect, test } from "bun:test";
import { evaluate } from "./mandatory-guards-helpers";

describe("mandatory no-sandbox review guards for environment and tool dispatch", () => {
  test.each([
    "gh pr view 42 -wc=false",
    "grep -Heneedle /etc/passwd",
    "GIT_EXTERNAL_DIFF=helper git diff",
    "PATH=. xcodebuildmcp tools",
    "xcrun sh -c 'echo ok'",
    "xcrun env PATH=. swift test",
    "EDITOR=/tmp/helper git commit",
    "VISUAL=/tmp/helper git commit",
    "PAGER=./helper git log -1",
    "TMPDIR=/etc sort README.md",
    "DEVELOPER_DIR=./attacker xcrun simctl list",
    "TOOLCHAINS=attacker xcrun simctl list",
    "SDKROOT=attacker xcrun simctl list",
    "env TOOLCHAINS=attacker xcrun simctl list",
    "xcrun --toolchain attacker simctl list",
    "xcrun --sdk attacker simctl list",
    "DEVELOPER_DIR=/tmp xcodebuild -version",
    "HOME=. xcodebuildmcp tools",
    "CFFIXED_USER_HOME=. xcodebuildmcp tools",
    "LESSOPEN=./helper less README.md",
    "LESSCLOSE=./helper less README.md",
    "GNUPGHOME=/tmp/gpg git commit -S -m test",
    "FFREPORT=file=/tmp/report ffprobe README.md",
    "CC=/tmp/helper swift build",
    "SWIFT_EXEC=/tmp/helper swift build",
    "xcrun sh script.sh",
    "xcrun bash script.sh",
    "xcrun sh",
    "xcrun git merge topic",
    "xcrun git rebase main",
    "xcrun git tag v1",
    "xcrun python3 script.py",
    "xcrun swift -repl",
    "xcrun swift -lldb-repl",
    "xcrun swift -load-plugin-executable /tmp/helper#Plugin Source.swift",
    "xcrun swift package plugin Attacker",
    "xcrun swift-frontend",
    "xcrun swift-frontend -repl",
    "xcrun swiftc --driver-mode=swift Source.swift",
    "xcrun swiftc -driver-use-frontend-path /tmp/helper Source.swift",
    "xcrun swiftc -ld-path=/tmp/helper Source.swift",
    "xcrun swiftc -Xllvm -load=/tmp/helper Source.swift",
    "xcrun swiftc -filelist /tmp/files.txt",
    "xcrun swiftc -vfsoverlay /tmp/map.yaml Source.swift",
    "xcrun swiftc -gcc-toolchain /tmp/evil -typecheck Source.swift",
    "xcrun swiftc -gcc-toolchain=/tmp/evil -typecheck Source.swift",
    "xcrun swiftc -lto-library /tmp/evil.dylib Source.swift",
    "xcrun swiftc -lto-library=/tmp/evil.dylib Source.swift",
    "xcrun swiftc -Xclang-linker -load -Xclang-linker /tmp/evil.dylib Source.swift",
    "swiftc -gcc-toolchain=/tmp/evil -typecheck Source.swift",
    "xcrun make -f /tmp/Makefile",
    "xcrun swift package format-source-code",
    "xcrun swift package --toolchain /tmp/evil describe",
    "xcrun swift package --toolset /tmp/toolset.json describe",
    "xcrun swift package --swift-sdks-path /tmp --swift-sdk attacker describe",
    "xcrun swift build --toolchain /tmp/evil",
    "xcrun swift build --toolset /tmp/toolset.json",
    "swift build --toolchain /tmp/evil",
    "swift build -Xswiftc -ld-path=/tmp/helper",
    "xcrun clang -fplugin=/tmp/helper.dylib Source.c",
    "xcrun clang -fpass-plugin=/tmp/helper.dylib Source.c",
    "xcrun clang -Xclang -load -Xclang /tmp/helper.dylib Source.c",
    "xcrun clang @/tmp/args.rsp",
    "xcrun clang --config=/tmp/clang.cfg Source.c",
    "xcrun clang Source.c -B/tmp/attacker-tools",
    "xcrun clang Source.c -B /tmp/attacker-tools",
    "xcrun clang Source.c -fuse-ld=/tmp/helper",
    "xcrun clang Source.c --ld-path=/tmp/helper",
    "xcrun clang Source.c -Xlinker -lto_library -Xlinker /tmp/evil.dylib",
    "xcrun clang Source.c -Wl,-plugin,/tmp/helper.dylib",
    "COMPILER_PATH=/tmp/attacker-tools xcrun clang Source.c",
    "GCC_EXEC_PREFIX=/tmp/attacker-tools xcrun clang Source.c",
    "CCC_ADD_ARGS=-fplugin=/tmp/evil.dylib xcrun clang Source.c",
    "xcrun swift-run Tool",
    "xcrun swift-package plugin Attacker",
    "xcrun swift-package format-source-code",
    "xcrun swift-api-digester -load-plugin-executable /tmp/helper#P",
    "xcrun swift-symbolgraph-extract -load-plugin-executable /tmp/helper#P",
    "xcrun clang-cache -fplugin=/tmp/helper.dylib Source.c",
    "xcrun clang-cache @/tmp/args.rsp",
    "xcrun cc -fplugin=/tmp/helper.dylib Source.c",
    "xcrun gcc -fplugin=/tmp/helper.dylib Source.c",
    "xcrun g++ @/tmp/args.rsp",
    "xcrun cpp @/tmp/args.rsp",
    "xcrun clang -fcas-plugin-path /tmp/helper.dylib Source.c",
    "xcrun clang -ccc-install-dir /tmp Source.c",
    "xcrun clang -ccc-gcc-name /tmp/helper Source.c",
    "xcrun clang -ivfsoverlay /tmp/map.yaml Source.c",
    "xcrun clang -vfsoverlay /tmp/map.yaml Source.c",
    "xcrun dsymutil -cas-plugin-path /tmp/helper.dylib App",
    "xcrun llvm-cas --fcas-plugin-path=/tmp/helper.dylib",
    "xcrun clang-cas-test --fcas-plugin-path=/tmp/helper.dylib",
    "xcrun ld -lto_library /tmp/libLTO.dylib -o App input.o",
    "xcrun ld @/tmp/args.rsp",
    "xcrun mig -cc /tmp/helper defs.defs",
    "xcrun mig -migcom /tmp/helper defs.defs",
    "xcrun rpcgen -Y /tmp defs.x",
    "xcrun clangd --query-driver=/tmp/helper",
    "xcrun sourcekit-lsp -Xclangd --query-driver=/tmp/helper",
    "xcrun sourcekit-lsp -Xclangd=--query-driver=/tmp/helper",
  ])("reviews an effectful option despite a broad user allow: %s", async (command) => {
    expect((await evaluate(command, true)).decision).toBe("review");
  });
});
