import { describe, expect, test } from "bun:test";
import { evaluate } from "./mandatory-guards-helpers";

describe("mandatory no-sandbox review guards for developer helpers", () => {
  test.each([
    "xcrun sourcekit-lsp -Xswiftc=-load-plugin-library -Xswiftc=/tmp/helper",
    "xcrun sourcekit-lsp -Xcc=-fplugin=/tmp/helper.dylib",
    "xcrun sourcekit-lsp -Xlinker=-lto_library -Xlinker=/tmp/libLTO.dylib",
    "xcrun clangd @/tmp/args.rsp",
    "xcrun dsymutil @/tmp/args.rsp",
    "xcrun llvm-cas @/tmp/args.rsp",
    "xcrun llvm-cov show --Xdemangler=/tmp/helper App",
    "xcrun llvm-cov show --Xdemangler /tmp/helper App",
    "xcrun llvm-cov @/tmp/args.rsp",
    "xcrun tapi installapi -Xparser -load -Xparser /tmp/helper.dylib Headers",
    "xcrun appintentsmetadataprocessor --toolchain-dir /tmp/evil --source-file-list /tmp/list",
    "xcrun appintentsmetadataprocessor --toolchain-dir=/tmp/evil --source-file-list /tmp/list",
    "xcrun appintentsmetadataprocessor -c /tmp/const-values",
    "xcrun xccov generate --toolchain attacker --json '{}'",
    "xcrun xctrace record --device 00000000-0000-0000-0000-000000000000 --package /tmp/evil.instrpkg --template 'Time Profiler' --launch -- com.example.App",
    "xcrun xctrace record --device 00000000-0000-0000-0000-000000000000 --template /tmp/evil.tracetemplate --launch -- com.example.App",
    "SWIFT_DRIVER_SWIFTSCAN_LIB=/tmp/helper.dylib swift build",
    "SWIFT_DRIVER_TOOLCHAIN_CASPLUGIN_LIB=/tmp/helper.dylib swift build",
    "SWIFT_DRIVER_FLAGS=-load-plugin-library=/tmp/helper swift build",
    "SWIFTPM_CUSTOM_BINDIR=/tmp/bin swift build",
    "SWIFTPM_UNSAFE_FLAGS=-load-plugin-library=/tmp/helper swift build",
    "SWIFT_EXEC_MANIFEST=/tmp/swift swift build",
    "SWIFT_API_DIGESTER=/tmp/helper swift build",
    "TOOLCHAINS_DIR=/tmp/toolchains swift build",
    "CLANG_CONFIG_PATH=/tmp/clang.cfg xcrun clang Source.c",
    "LLVM_CACHE_PLUGIN_PATH=/tmp/helper.dylib xcrun clang Source.c",
    "LLVM_SYMBOLIZER_PATH=/tmp/helper xcrun clang Source.c",
    "COMMAND_YACC=/tmp/helper xcrun yacc input.y",
    "DOCC_LINK_RESOLVER_EXECUTABLE=/tmp/helper xcrun docc convert Docs.docc",
    "LIBLTO_PATH=/tmp/helper.dylib xcrun lipo -info App",
    "LIBLTO_PATH=/tmp/helper.dylib xcrun strings App",
    "OTOOL_PATH=/tmp/helper xcrun otool -L App",
    "xcrun otool -object-tool-path /tmp/helper -t App",
    "SOURCEKIT_TOOLCHAIN_PATH=/tmp/evil xcrun sourcekit-lsp",
    "SOURCEKIT_PATH=/tmp/helper.dylib xcrun sourcekit-lsp",
    "xcrun c89 -fplugin=/tmp/helper.dylib Source.c",
    "xcrun c99 -Xclang -load -Xclang /tmp/helper.dylib Source.c",
    "xcrun metal-package-builder '\"; /tmp/helper; echo \"'",
    "xcrun python3.9 -c 'print(1)'",
    "xcrun pip3 install attacker",
    "xcrun pip3.9 install attacker",
    "xcrun mcpbridge",
    "xcrun agent skills export --output-dir /tmp/skills",
    "xcrun xcdebug /tmp/helper",
    "xcrun swift-build-tool -f /tmp/build.llbuild",
    "xcrun clang-format-diff.py -binary /tmp/helper",
    "xcrun clang-format-diff.py -i",
    "xcrun ba-serve /tmp/assets",
    "xcrun xed Project.xcodeproj",
    "xcrun opendiff left right",
    "xcrun m4 payload.m4",
    "xcrun gm4 payload.m4",
    "xcrun pydoc3 /tmp/module.py",
    "xcrun git-receive-pack repo",
    "xcrun git-upload-pack repo",
    "xcrun git-shell -c /tmp/helper",
    "xcrun scalar clone https://example.invalid/repo",
    "xcrun scalar delete repo",
    "xcrun bison -S /tmp/evil-skeleton input.y",
    "BISON_PKGDATADIR=/tmp xcrun bison input.y",
    "xcrun leaks --atExit -- /tmp/helper",
    "xcrun xctrace record --template 'Time Profiler' --launch -- /tmp/helper",
    "xcrun xctrace record --device blanboom-studio --launch -- /tmp/helper",
    "xcrun xctrace record --device 4770BE00-01F0-5B28-9513-9D08230BD526 --launch -- /tmp/helper",
    "xcrun xctrace record --device 00000000-0000-0000-0000-000000000000 --template 'Time Profiler' --launch -- com.example.App",
    "xcrun xctest /tmp/Attacker.xctest",
    "xcrun swiftc @/tmp/args.rsp",
    "xcrun swift-plugin-server",
    "XCODE_XCCONFIG_FILE=/tmp/attacker.xcconfig xcodebuild build",
    "xcodebuild -xcconfig /tmp/attacker.xcconfig build",
    "xcodebuild CC=/tmp/helper build",
    "xcodebuild SWIFT_EXEC=/tmp/helper build",
    "xcodebuild LD=/tmp/helper build",
    "xcodebuild -toolchain attacker build",
    "xcodebuild -sdk /tmp/Attacker.sdk build",
    "xcodebuild TOOLCHAINS=attacker build",
    "xcodebuild SDKROOT=/tmp/Attacker.sdk build",
    "xcodebuild OTHER_SWIFT_FLAGS=-load-plugin-executable=/tmp/helper build",
    "xcodebuild OTHER_CFLAGS=-B/tmp/attacker-tools build",
    "xcodebuild OTHER_SWIFT_FLAGS=-ld-path=/tmp/helper build",
    "xcodebuild OTHER_SWIFT_FLAGS=\"-ld-path /tmp/helper\" build",
    "xcodebuild OTHER_SWIFT_FLAGS=\"-filelist /tmp/files.txt\" build",
    "xcodebuild OTHER_CFLAGS=-fcas-plugin-path=/tmp/helper.dylib build",
    "xcodebuild OTHER_CFLAGS=\"-ccc-install-dir /tmp\" build",
    "xcodebuild OTHER_SWIFT_FLAGS=-gcc-toolchain=/tmp/evil build",
    "xcodebuild OTHER_SWIFT_FLAGS=-lto-library=/tmp/evil.dylib build",
    "xcodebuild OTHER_SWIFT_FLAGS=-Xclang-linker=-load build",
    "xcodebuild LIBTOOL=/tmp/helper build",
    "xcodebuild LEX=/tmp/helper build",
    "xcodebuild PATH=/tmp build",
    "xcodebuild BASH_ENV=/tmp/evil build",
    "xcodebuild DYLD_INSERT_LIBRARIES=/tmp/helper.dylib build",
    "sh script.sh",
    "sh /etc/passwd",
    "arch sudo id",
    "caffeinate sh script.sh",
    "find . -exec sh script.sh ;",
    "launchctl submit -l task -- sh script.sh",
    "script output.log sh script.sh",
    "ssh host command",
    "dd if=/dev/zero of=/etc/passwd",
    "(echo hi) > output",
    "{ echo hi; } > output",
    "! echo hi > output",
    "echo hi | grep hi > output",
    "echo hi && grep hi > output",
    "echo hi || grep hi > output",
    "> output; xcodebuildmcp tools",
    "PATH=.; xcodebuildmcp tools",
    "HOME=.; xcodebuildmcp tools",
    "EDITOR=./helper; git commit -S -m test",
    "DEVELOPER_DIR=./attacker; xcrun simctl list",
    "git commit -aF/etc/passwd --dry-run",
    "git blame --textconv README.md",
    "git branch --color new",
    "git tag --color new",
  ])("reviews an effectful option despite a broad user allow: %s", async (command) => {
    expect((await evaluate(command, true)).decision).toBe("review");
  });
});
