import { describe, expect, test } from "bun:test";
import { evaluateRules } from "../src/rules";
import { userPolicy } from "./user-command-policy-helpers";

describe("Codex-derived user command review policy", () => {
  test.each([
    "swift run Tool",
    "swift script.swift",
    "gh issue create",
    "xcodebuildmcp tools | unknown-command",
    "git commit --no-gpg-sign -m test",
    "git -c commit.gpgsign=false commit -m test",
    "git -c gpg.format=ssh commit -S -m test",
    "git commit --no-gpg -m test",
    "git commit --no-gpg-s -m test",
    "xcrun swift script.swift",
    "xcrun --run swift script.swift",
    "cat script.swift | xcrun swift -",
    "xcrun /usr/bin/swift script.swift",
    "xcrun --run /usr/bin/swift script.swift",
    "xcrun env swift script.swift",
    "xcrun swift-frontend -interpret script.swift",
    "xcrun sh -c 'echo ok'",
    "xcrun env PATH=. swift test",
    "TOOLCHAINS=attacker xcrun simctl list",
    "SDKROOT=attacker xcrun simctl list",
    "env TOOLCHAINS=attacker xcrun simctl list",
    "xcrun --toolchain attacker simctl list",
    "xcrun --sdk attacker simctl list",
    "EDITOR=/tmp/helper git commit",
    "HOME=. xcodebuildmcp tools",
    "DEVELOPER_DIR=./attacker xcodebuild -version",
    "xcrun sh script.sh",
    "xcrun bash script.sh",
    "xcrun git merge topic",
    "xcrun git rebase main",
    "xcrun git tag v1",
    "xcrun python3 script.py",
    "xcrun swift -repl",
    "xcrun swift -lldb-repl",
    "xcrun swift -load-plugin-executable /tmp/helper#Plugin Source.swift",
    "xcrun swift package plugin Attacker",
    "xcrun swift-frontend",
    "xcrun swift-frontend -repl",
    "xcrun swiftc --driver-mode=swift Source.swift",
    "xcrun swiftc -driver-use-frontend-path /tmp/helper Source.swift",
    "xcrun swiftc -ld-path=/tmp/helper Source.swift",
    "xcrun swiftc -Xllvm -load=/tmp/helper Source.swift",
    "xcrun swiftc -filelist /tmp/files.txt",
    "xcrun swiftc -vfsoverlay /tmp/map.yaml Source.swift",
    "xcrun swiftc -gcc-toolchain /tmp/evil -typecheck Source.swift",
    "xcrun swiftc -gcc-toolchain=/tmp/evil -typecheck Source.swift",
    "xcrun swiftc -lto-library /tmp/evil.dylib Source.swift",
    "xcrun swiftc -lto-library=/tmp/evil.dylib Source.swift",
    "xcrun swiftc -Xclang-linker -load -Xclang-linker /tmp/evil.dylib Source.swift",
    "xcrun make -f /tmp/Makefile",
    "xcrun swift package format-source-code",
    "xcrun swift package --toolchain /tmp/evil describe",
    "xcrun swift package --toolset /tmp/toolset.json describe",
    "xcrun swift package --swift-sdks-path /tmp --swift-sdk attacker describe",
    "xcrun swift build --toolchain /tmp/evil",
    "xcrun swift build --toolset /tmp/toolset.json",
    "swift build --toolchain /tmp/evil",
    "swift build -Xswiftc -ld-path=/tmp/helper",
    "xcrun clang -fplugin=/tmp/helper.dylib Source.c",
    "xcrun clang -fpass-plugin=/tmp/helper.dylib Source.c",
    "xcrun clang -Xclang -load -Xclang /tmp/helper.dylib Source.c",
    "xcrun clang @/tmp/args.rsp",
    "xcrun clang --config=/tmp/clang.cfg Source.c",
    "xcrun clang Source.c -B/tmp/attacker-tools",
    "xcrun clang Source.c -B /tmp/attacker-tools",
    "xcrun clang Source.c -fuse-ld=/tmp/helper",
    "xcrun clang Source.c --ld-path=/tmp/helper",
    "xcrun clang Source.c -Xlinker -lto_library -Xlinker /tmp/evil.dylib",
    "xcrun clang Source.c -Wl,-plugin,/tmp/helper.dylib",
    "COMPILER_PATH=/tmp/attacker-tools xcrun clang Source.c",
    "GCC_EXEC_PREFIX=/tmp/attacker-tools xcrun clang Source.c",
    "CCC_ADD_ARGS=-fplugin=/tmp/evil.dylib xcrun clang Source.c",
    "xcrun swift-run Tool",
    "xcrun swift-package plugin Attacker",
    "xcrun swift-package format-source-code",
    "xcrun swift-api-digester -load-plugin-executable /tmp/helper#P",
    "xcrun swift-symbolgraph-extract -load-plugin-executable /tmp/helper#P",
    "xcrun clang-cache -fplugin=/tmp/helper.dylib Source.c",
    "xcrun clang-cache @/tmp/args.rsp",
    "xcrun cc -fplugin=/tmp/helper.dylib Source.c",
    "xcrun gcc -fplugin=/tmp/helper.dylib Source.c",
    "xcrun g++ @/tmp/args.rsp",
    "xcrun cpp @/tmp/args.rsp",
    "xcrun clang -fcas-plugin-path /tmp/helper.dylib Source.c",
    "xcrun clang -ccc-install-dir /tmp Source.c",
    "xcrun clang -ccc-gcc-name /tmp/helper Source.c",
    "xcrun clang -ivfsoverlay /tmp/map.yaml Source.c",
    "xcrun clang -vfsoverlay /tmp/map.yaml Source.c",
    "xcrun dsymutil -cas-plugin-path /tmp/helper.dylib App",
    "xcrun llvm-cas --fcas-plugin-path=/tmp/helper.dylib",
    "xcrun clang-cas-test --fcas-plugin-path=/tmp/helper.dylib",
    "xcrun ld -lto_library /tmp/libLTO.dylib -o App input.o",
    "xcrun ld @/tmp/args.rsp",
    "xcrun mig -cc /tmp/helper defs.defs",
    "xcrun mig -migcom /tmp/helper defs.defs",
    "xcrun rpcgen -Y /tmp defs.x",
    "xcrun clangd --query-driver=/tmp/helper",
    "xcrun sourcekit-lsp -Xclangd --query-driver=/tmp/helper",
    "xcrun sourcekit-lsp -Xclangd=--query-driver=/tmp/helper",
    "xcrun sourcekit-lsp -Xswiftc=-load-plugin-library -Xswiftc=/tmp/helper",
    "xcrun sourcekit-lsp -Xcc=-fplugin=/tmp/helper.dylib",
    "xcrun sourcekit-lsp -Xlinker=-lto_library -Xlinker=/tmp/libLTO.dylib",
    "xcrun clangd @/tmp/args.rsp",
    "xcrun dsymutil @/tmp/args.rsp",
    "xcrun llvm-cas @/tmp/args.rsp",
    "xcrun llvm-cov show --Xdemangler=/tmp/helper App",
    "xcrun llvm-cov show --Xdemangler /tmp/helper App",
    "xcrun llvm-cov @/tmp/args.rsp",
    "xcrun tapi installapi -Xparser -load -Xparser /tmp/helper.dylib Headers",
    "xcrun appintentsmetadataprocessor --toolchain-dir /tmp/evil --source-file-list /tmp/list",
    "xcrun appintentsmetadataprocessor --toolchain-dir=/tmp/evil --source-file-list /tmp/list",
    "xcrun appintentsmetadataprocessor -c /tmp/const-values",
    "xcrun xccov generate --toolchain attacker --json '{}'",
    "xcrun xctrace record --device 00000000-0000-0000-0000-000000000000 --package /tmp/evil.instrpkg --template 'Time Profiler' --launch -- com.example.App",
    "xcrun xctrace record --device 00000000-0000-0000-0000-000000000000 --template /tmp/evil.tracetemplate --launch -- com.example.App",
    "SWIFT_DRIVER_SWIFTSCAN_LIB=/tmp/helper.dylib swift build",
    "SWIFT_DRIVER_TOOLCHAIN_CASPLUGIN_LIB=/tmp/helper.dylib swift build",
    "SWIFT_DRIVER_FLAGS=-load-plugin-library=/tmp/helper swift build",
    "SWIFTPM_CUSTOM_BINDIR=/tmp/bin swift build",
    "SWIFTPM_UNSAFE_FLAGS=-load-plugin-library=/tmp/helper swift build",
    "SWIFT_EXEC_MANIFEST=/tmp/swift swift build",
    "SWIFT_API_DIGESTER=/tmp/helper swift build",
    "TOOLCHAINS_DIR=/tmp/toolchains swift build",
    "CLANG_CONFIG_PATH=/tmp/clang.cfg xcrun clang Source.c",
    "LLVM_CACHE_PLUGIN_PATH=/tmp/helper.dylib xcrun clang Source.c",
    "LLVM_SYMBOLIZER_PATH=/tmp/helper xcrun clang Source.c",
    "COMMAND_YACC=/tmp/helper xcrun yacc input.y",
    "DOCC_LINK_RESOLVER_EXECUTABLE=/tmp/helper xcrun docc convert Docs.docc",
    "LIBLTO_PATH=/tmp/helper.dylib xcrun lipo -info App",
    "LIBLTO_PATH=/tmp/helper.dylib xcrun strings App",
    "OTOOL_PATH=/tmp/helper xcrun otool -L App",
    "xcrun otool -object-tool-path /tmp/helper -t App",
    "SOURCEKIT_TOOLCHAIN_PATH=/tmp/evil xcrun sourcekit-lsp",
    "SOURCEKIT_PATH=/tmp/helper.dylib xcrun sourcekit-lsp",
    "xcrun c89 -fplugin=/tmp/helper.dylib Source.c",
    "xcrun c99 -Xclang -load -Xclang /tmp/helper.dylib Source.c",
    "xcrun metal-package-builder '\"; /tmp/helper; echo \"'",
    "xcrun python3.9 -c 'print(1)'",
    "xcrun pip3 install attacker",
    "xcrun pip3.9 install attacker",
    "xcrun mcpbridge",
    "xcrun agent skills export --output-dir /tmp/skills",
    "xcrun xcdebug /tmp/helper",
    "xcrun swift-build-tool -f /tmp/build.llbuild",
    "xcrun clang-format-diff.py -binary /tmp/helper",
    "xcrun clang-format-diff.py -i",
    "xcrun ba-serve /tmp/assets",
    "xcrun xed Project.xcodeproj",
    "xcrun opendiff left right",
    "xcrun m4 payload.m4",
    "xcrun gm4 payload.m4",
    "xcrun pydoc3 /tmp/module.py",
    "xcrun git-receive-pack repo",
    "xcrun git-upload-pack repo",
    "xcrun git-shell -c /tmp/helper",
    "xcrun scalar clone https://example.invalid/repo",
    "xcrun scalar delete repo",
    "xcrun bison -S /tmp/evil-skeleton input.y",
    "BISON_PKGDATADIR=/tmp xcrun bison input.y",
    "xcrun leaks --atExit -- /tmp/helper",
    "xcrun xctrace record --template 'Time Profiler' --launch -- /tmp/helper",
    "xcrun xctrace record --device blanboom-studio --launch -- /tmp/helper",
    "xcrun xctrace record --device 4770BE00-01F0-5B28-9513-9D08230BD526 --launch -- /tmp/helper",
    "xcrun xctrace record --device 00000000-0000-0000-0000-000000000000 --template 'Time Profiler' --launch -- com.example.App",
    "xcrun xctest /tmp/Attacker.xctest",
    "xcrun swiftc @/tmp/args.rsp",
    "xcrun swift-plugin-server",
    "XCODE_XCCONFIG_FILE=/tmp/attacker.xcconfig xcodebuild build",
    "xcodebuild -xcconfig /tmp/attacker.xcconfig build",
    "xcodebuild CC=/tmp/helper build",
    "xcodebuild SWIFT_EXEC=/tmp/helper build",
    "xcodebuild LD=/tmp/helper build",
    "xcodebuild -toolchain attacker build",
    "xcodebuild -sdk /tmp/Attacker.sdk build",
    "xcodebuild TOOLCHAINS=attacker build",
    "xcodebuild SDKROOT=/tmp/Attacker.sdk build",
    "xcodebuild OTHER_SWIFT_FLAGS=-load-plugin-executable=/tmp/helper build",
    "xcodebuild OTHER_CFLAGS=-B/tmp/attacker-tools build",
    "xcodebuild OTHER_SWIFT_FLAGS=-ld-path=/tmp/helper build",
    "xcodebuild OTHER_SWIFT_FLAGS=\"-ld-path /tmp/helper\" build",
    "xcodebuild OTHER_SWIFT_FLAGS=\"-filelist /tmp/files.txt\" build",
    "xcodebuild OTHER_CFLAGS=-fcas-plugin-path=/tmp/helper.dylib build",
    "xcodebuild OTHER_CFLAGS=\"-ccc-install-dir /tmp\" build",
    "xcodebuild OTHER_SWIFT_FLAGS=-gcc-toolchain=/tmp/evil build",
    "xcodebuild OTHER_SWIFT_FLAGS=-lto-library=/tmp/evil.dylib build",
    "xcodebuild OTHER_SWIFT_FLAGS=-Xclang-linker=-load build",
    "xcodebuild LIBTOOL=/tmp/helper build",
    "xcodebuild LEX=/tmp/helper build",
    "xcodebuild PATH=/tmp build",
    "xcodebuild BASH_ENV=/tmp/evil build",
    "xcodebuild DYLD_INSERT_LIBRARIES=/tmp/helper.dylib build",
  ])("reviews commands outside the trusted segment: %s", async (command) => {
    expect((await evaluateRules(userPolicy().rules, { command })).decision).toBe("review");
  });
});
