import { defaultRules } from "./default-rules";
import { DEFAULT_REVIEWER_POLICY } from "./prompt";
import type { ApprovalPolicy, ReviewConfig, RiskToolConfig, SelfProtectionConfig } from "./types";

export type DefaultReviewConnection = Pick<ReviewConfig, "baseURL" | "apiKey" | "model">;

export const DEFAULT_REVIEW_CONNECTION = {
  baseURL: "",
  apiKey: "",
  model: "",
} as const satisfies DefaultReviewConnection;

export const DEFAULT_REVIEW_MAX_RETRIES = 3;

export const DEFAULT_RISK_TOOL = {
  enabled: true,
  timeoutMs: 5_000,
  failOpen: false,
} as const satisfies RiskToolConfig;

export const DEFAULT_SELF_PROTECTION = {
  enabled: true,
} as const satisfies SelfProtectionConfig;

export const defaultPolicy = (connection: DefaultReviewConnection = DEFAULT_REVIEW_CONNECTION): ApprovalPolicy => ({
  review: {
    baseURL: connection.baseURL,
    apiKey: connection.apiKey,
    model: connection.model,
    timeoutMs: 45_000,
    maxScriptBytes: 20_000,
    maxToolCalls: 3,
    maxRetries: DEFAULT_REVIEW_MAX_RETRIES,
    contextMessages: 20,
    prompt: DEFAULT_REVIEWER_POLICY,
  },
  riskTool: DEFAULT_RISK_TOOL,
  selfProtection: DEFAULT_SELF_PROTECTION,
  rules: defaultRules(),
});

const defaultConfigObject = () => ({
  version: 2,
  allow_local_config: false,
  self_protection: DEFAULT_SELF_PROTECTION,
  review: {
    base_url: "https://api.example.com/v1",
    api_key: "your-api-key",
    model: "your-model-name",
    timeout_ms: 45_000,
    max_script_bytes: 20_000,
    max_tool_calls: 3,
    max_retries: DEFAULT_REVIEW_MAX_RETRIES,
    context_messages: 20,
  },
  tirith: {
    enabled: DEFAULT_RISK_TOOL.enabled,
    timeout_ms: DEFAULT_RISK_TOOL.timeoutMs,
    fail_open: DEFAULT_RISK_TOOL.failOpen,
  },
  rules: {
    deny: [],
    review: [],
    allow: [],
  },
});

export const defaultConfigJson = (_connection: DefaultReviewConnection = DEFAULT_REVIEW_CONNECTION): string => {
  const header = [
    "// CommandApproval config. JSON with comments are supported.",
    "// Project-local config is ignored unless this trusted global file sets allow_local_config to true.",
    "// Decision order: user rules, small built-in rules, Tirith, then LLM review.",
    "// A complete user allow or deny is terminal and skips every later stage.",
    "// Built-in rules are applied automatically; add only personal overrides below.",
    "// Unversioned and version 1 configs retire only the exact broad allows generated by older releases; version 2 preserves explicit rules.",
    "// Rule objects support scope: command|segment and an integer priority.",
    "// Pipeline/list commands short-circuit only when every static executable segment is allowed.",
    "// self_protection.enabled defaults to true and blocks edits to this policy via shell and file-edit tools.",
    "// Set review.base_url, review.api_key, and review.model explicitly.",
  ].join("\n");
  return `${header}\n${JSON.stringify(defaultConfigObject(), null, 2)}\n`;
};
